# Generated by Django 3.2.5 on 2022-02-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmerapp', '0012_purchased_reject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_date', models.DateField()),
                ('bidding_start_time', models.TimeField()),
                ('bidding_end_time', models.TimeField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.producttbl')),
            ],
        ),
    ]
