# Generated by Django 3.2.5 on 2022-02-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingproduct',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
