# Generated by Django 3.2.6 on 2022-02-27 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0005_auto_20220208_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingproduct',
            name='bidding_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biddingproduct',
            name='bidding_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Purchased_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('paid_amount', models.FloatField()),
                ('payment_id', models.CharField(max_length=300)),
                ('signature_hash', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sold_bd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidding.bid_sold')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
