# Generated by Django 3.1.4 on 2021-04-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0003_producttbl_upload_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttbl',
            name='upload_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmerapp.user_profile'),
        ),
    ]
