# Generated by Django 3.1.4 on 2021-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0007_purchased_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
