# Generated by Django 3.1.4 on 2021-04-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0008_contacttbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='farmer_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
