# Generated by Django 3.2.5 on 2021-09-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0009_user_profile_farmer_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttbl',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
