# Generated by Django 3.2.5 on 2021-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0010_producttbl_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttbl',
            name='product_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
