# Generated by Django 3.2.5 on 2021-09-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0011_alter_producttbl_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
