# Generated by Django 3.2.6 on 2022-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0012_purchased_reject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='sample')),
            ],
        ),
    ]
